### ISSUE TITLE
Print Media Queries and Icon

### ISSUE THREAD

**Issue by lisaratner** [rossettistone/bizport#51]
Converts page into a print friendly pdf

**Comment by rossettistone** [comment]
Yep, that could be valuable for entrepreneurs. Making websites print-ready can take a bit of work. If folks start using the site in this way, let's figure out what the key components of a good print-ready page would be and prioritize accordingly.

**Comment by lisaratner** [comment]
Users want. 
Menu -> Share -> Print
Does it need to save as a pdf first before printing?

**Comment by rossettistone** [comment]
Awesome! I'm actually not certain what the best way to go about this is. A couple of notes of how I'm thinking about it:
• Could be done with a print stylesheet, straight from the same page that's used in the browser.
• Could be done by moving the text content out of the page and then rendering it into two entirely different templates, one for web and one for print. In this case, I might even drop the content into PDF so that it can be easily saved as a flat document, in case that's also interesting to folks.

I'll ask around a bit to get advice on what's a good approach.

**Comment by lisaratner** [comment]
https://medium.com/designing-medium/printing-medium-stories-89f381b903c9#.ayxy8n351

**Comment by lisaratner** [comment]
<img width="1247" alt="screen shot 2016-04-20 at 8 36 36 pm" src="https://cloud.githubusercontent.com/assets/16671878/14697424/988a6d3e-0738-11e6-8d48-443801e34caa.png">

**Comment by lisaratner** [comment]
https://drive.google.com/open?id=0B6V6JxtkVuf9eFRleWRVYTVGbmM
