### ISSUE TITLE
Style Tweaks / Bug fixes

### ISSUE THREAD

**Issue by lisaratner** [rossettistone/bizport#75]
- [x] Note box -> dark grey. Step 4 has notes are in blue box
- [x] Center readmore expand icon on mobile

~~some sections have fade but no extra content below. Like Step 4, availability of name section.~~ (duplicate of #53, now resolved)

- [x] Footer text -> white
- [x] Change "next page" CTA at bottom of screen to dark grey. Make font size of H2. 
- [x] Step 5 has weird spacing below Permit Status on Mobile
- [x] Change link font to Open Sans. Numbers render really strange in Raleway.
- [x] Start the gradient higher for the expand / collapse
- [x] Add white link icon to active state
- [x] Make all links open a new tab vs. replacing the current page - makes wayfinding hard
- [x] Remove scroll on collapse from readmore blocks. New UX pattern is needed here, TBD.
- [x] make phone icon consistently sized with the email icon.
- [x] Only expand readmore blocks when content is at least 2x height of collapsed block
- [x] Increase H3 to 18px rems equivalent
- [x] Underline link text beneath icons instead. Bold "Step N:" for each one as well.
- [x] Add hover state underline to "My Checklist"
- [x] Add hover state underline to all navbar items

**Comment by rossettistone** [comment]
__Step 5 has weird spacing below Permit Status on Mobile__: This is actually an iframe of a form from the city's website, and I had to pick a height that retained basic usability when it was embedded, though I recognize it doesn't look awesome. It's an outstanding question in the content doc whether or not this embed is a keeper at all, or should just be cut entirely. Before we solve the height question, what do you think about that?

__Apply H2 styling to Contact and FAQ page headers__: Let's talk through what the header on these pages should look like. Feels a little different than the "start a business" step pages.

__Home Page Icons should be dark_blue instead of black__: Can do. Just need those icons in the desired color. Let's sit down together to figure out the box shadow styling.

__Add a smaller link under the Next Step CTA to go to the last step__: What should that link look like? Text only? Different color button?
